exclude:
  female_exact:
    - big ass
    - big areolae
    - big muscles
    - big nipples
    - big vagina
    - big clit
    - piss drinking
    - futanari
    - raccoon girl
    - amputee
    - huge breasts
    - dickgirl on dickgirl
    - dickgirl on female
    - futanarization
    - ttf threesome

  any_namespace:
    - furry
    - robot
    - weight gain
    - collar

  animal_content:
    - bestiality
    - low bestiality
    - animal on animal
    - animal on furry
